### ISSUE TITLE
FR Image Classification template with drop down bar

### ISSUE THREAD

**Issue by gloriamacia** [aws-samples/amazon-a2i-sample-task-uis#3]
I would like to request a feature. An image classification template (or other example) with a drop down bar: image-classification.liquid.html

it would be very useful when the number of classes is very large (>100) and cannot fit well in the screen

**Comment by samuel-henry** [comment]
Thank you for this request. 

I just added this example: https://github.com/aws-samples/amazon-a2i-sample-task-uis/blob/master/images/image-classification-with-dropdown-select.liquid.html

Note that you can also dynamically generate the select option list using the Liquid framework's looping technology: https://shopify.github.io/liquid/tags/iteration/

Here's a jsfiddle showing the template with a placeholder image so you can see it in interactive mode: https://jsfiddle.net/pza9nj3r/

Please let me know if this meets your needs.

Thank you
Sam

**Comment by gloriamacia** [comment]
@samuel-henry these templates are super nice! I checked out https://shopify.github.io/liquid/tags/iteration/, I have my >1000 categories in a csv (or also in a python list, series, etc) how can I pass them to a liquid collection object to avoid to type each of these manually? Or given the number of categories, even better than a dropdown bar, is there a way to have an autocomplete field, i.e. user starts typing a category and the interface shows the possible options dynamically. Trying to see how to squeeze so many categories in a UI...

**Comment by samuel-henry** [comment]
These resources may be useful to see how to pass python dataframes in to create a dynamic list in the annotation tool:

https://aws.amazon.com/blogs/machine-learning/using-amazon-sagemaker-with-amazon-augmented-ai-for-human-review-of-tabular-data-and-ml-predictions/

https://github.com/aws-samples/amazon-a2i-sample-jupyter-notebooks/blob/master/Amazon%20Augmented%20AI%20(Amazon%20A2I)%20Integration%20with%20tabular%20data.ipynb

Some of our annotation components (eg crowd-semantic-segmentation, crowd-instance-segmentation, crowd-bounding-box, crowd-polygon, crowd-polyline, crowd-line, and crowd-keypoint) support the search/filter/auto-complete functionality you describe for cases when there are a lot of categories. Unfortunately our classification components do not currently support that functionality, but this is useful feedback.

Please let me know if you have any additional questions or feedback.
